import { Dimensions, StyleSheet } from 'react-native'

export const ProfileScreenStyle = StyleSheet.create({
  DragToRefreshContainer: {
    alignItems: 'center',
    borderRadius: 50,
    display: 'flex',
    height: 50,
    position: 'absolute',
    top: -20,
    width: '100%',
    zIndex: 10,
  },
  DragToRefreshText: {
    backgroundColor: '#F4F4F5',
    borderRadius: 10,
    color: '#000',
    paddingHorizontal: 30,
    paddingVertical: 6,
    position: 'relative',
    top: 35,
  },
  ProfileScreenContiner: {
    backgroundColor: '#ffffff',
    height: '100%',
    paddingTop: 20,
    position: 'relative',
    width: '100%',
    zIndex: 5,
  },
  UserProfileContainer: {
    alignItems: 'center',
    borderColor: '#E4E7EA',
    borderRadius: 25,
    borderWidth: 3,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 40,
    paddingVertical: 40,
  },
  UserProfileTexts: {
    alignItems: 'flex-start',
    color: '#000',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Poppins',
    justifyContent: 'center',
    width: '60%',
  },
  ProfileImage: {
    borderRadius: 50,
    height: 72,
    width: 72,
  },
  UserProfileName: {
    color: '#000',
    fontFamily: 'Poppins',
    fontSize: 26,
    fontWeight: '700',
    width: '100%',
  },

  ContainerDate: {
    color: '#000',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
    textAlign: 'left',
    width: '100%',
  },

  greenBarProfile: {
    borderColor: '#87E1B9',
    borderWidth: 2,
    width: 30,
  },

  ContainerText: {
    color: '#000',
    fontFamily: 'Poppins',
    fontSize: 16,
  },

  UserFavMostContainer: {
    display: 'flex',
    flexDirection: 'row',
    height: 80,
    justifyContent: 'space-evenly',
    marginTop: 40,
  },
  UserFavoriteTypeContainer: {
    alignItems: 'center',
    borderRadius: 25,
    color: '#ffffff',
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  UserResetContainer: {
    backgroundColor: 'blue',
    width: '48%',
  },
  UserFavoriteTexts: {
    color: '#fff',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
  },
  UserFavoriteTextLabel: {
    color: '#fff',
    fontSize: 16,
  },
  UserFavoriteTextNumber: {
    color: '#fff',
    fontSize: 16,
  },
  ScoreboardText: {
    font: '#d0d0d0',
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  ProductContainer: {
    alignItems: 'center',
    borderRadius: 20,
    display: 'flex',
    elevation: 2,
    justifyContent: 'center',
    paddingVertical: 24,
    shadowColor: '#171717',
  },
  resetStatisticsContainer: {
    alignItems: 'center',
    borderRadius: 25,
    display: 'flex',
    flexDirection: 'row',
    height: 80,
    justifyContent: 'center',
    marginVertical: 10,
    width: '100%',
  },

  resetStatistics: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
  },
  resetStatisticsText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '600',
  },

  logOutContainer: {
    alignItems: 'center',
    backgroundColor: '#FEEBE6',
    borderColor: '#fcc0b1',
    borderRadius: 25,
    display: 'flex',
    flexDirection: 'row',
    height: 80,
    justifyContent: 'space-evenly',
    marginVertical: 10,
    width: '100%',
  },

  logOutTouchable: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
  },

  logOutText: {
    color: '#000',
    fontSize: 20,
    fontWeight: '500',
  },
  shadowProp: {
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
})
