import { StyleSheet } from 'react-native'

export const ProfileScreenStyle = StyleSheet.create({
  DragToRefreshContainer: {
    alignItems: 'center',
    borderRadius: 50,
    display: 'flex',
    height: 50,
    position: 'absolute',
    top: -20,
    width: '100%',
    zIndex: 10,
  },
  DragToRefreshText: {
    backgroundColor: '#F4F4F5',
    borderRadius: 10,
    color: '#000',
    paddingHorizontal: 30,
    paddingVertical: 6,
    position: 'relative',
    top: 35,
  },
  ProfileScreenContiner: {
    backgroundColor: '#ffffff',
    height: '100%',
    paddingTop: 20,
    position: 'relative',
    width: '100%',
    zIndex: 5,
  },
  UserProfileContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    padding: 20,
  },
  UserProfileTexts: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    height: 64,
    justifyContent: 'center',
    marginBottom: 25,
  },
  ProfileImage: {
    borderRadius: 50,
    height: 56,
    marginRight: 20,
    width: 56,
  },
  UserProfileName: {
    color: '#000',
    fontSize: 20,
    fontWeight: '700',
  },
  logOut: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    marginLeft: 25,
  },
  UserProfileJoinedDate: {
    color: '#787879',
    fontSize: 10,
    fontWeight: '700',
  },

  UserProfileBadges: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  ContainerBadge: {
    alignItems: 'center',
    backgroundColor: '#F4F4F5',
    borderColor: '#96A0D0',
    borderRadius: 8,
    borderWidth: 1,
    display: 'flex',
    height: 72,
    justifyContent: 'center',
    width: '46%',
  },
  ContainerText: {
    fontFamily: 'Poppins',
    fontSize: 16,
  },
  ContainerDate: {
    fontFamily: 'Poppins',
    fontSize: 14,
    textAlign: 'center',
    width: '60%',
  },

  UserFavMostContainer: {
    display: 'flex',
    flexDirection: 'row',
    height: 64,
    justifyContent: 'space-evenly',
  },
  UserFavoriteTypeContainer: {
    alignItems: 'center',
    borderColor: '#96A0D0',
    borderRadius: 4,
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  UserResetContainer: {
    backgroundColor: 'blue',
    width: '48%',
  },
  UserFavoritePetIcon: {
    height: 46,
    marginRight: 10,
    width: 46,
  },
  UserFavoriteTexts: {
    display: 'flex',
  },
  UserFavoriteTextLabel: {
    color: '#fff',
    fontSize: 16,
  },
  UserFavoriteTextNumber: {
    color: '#fff',
    fontSize: 16,
  },
  ScoreboardText: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 30,
    textAlign: 'center',
  },
  ProductContainer: {
    alignItems: 'center',
    borderRadius: 5,
    display: 'flex',
    height: 100,
    justifyContent: 'center',
    margin: 8,
  },
  resetStatisticsContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 20,
    width: '100%',
  },
  resetStatistics: {
    alignItems: 'center',
    backgroundColor: '#266DD3',
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 1.5,
    display: 'flex',
    height: 48,
    justifyContent: 'center',
    width: 156,
  },
  resetStatisticsText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },

  logOutText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
})
